wip

diff --git a/run b/run
--- a/run
+++ b/run
@@ -2,6 +2,7 @@
 
 THIS_DIR=${0:A:h}
 APP=$THIS_DIR/verylog
+INTERPRETER=${INTERPRETER:-true}
 
 if [[ $# -eq 0 ]]; then
     echo "usage: $0 [parser options] <verilog file>"
@@ -35,22 +36,47 @@ IVLPP=$IVL_DIR/ivlpp/ivlpp
 
 LOGFILE=$THIS_DIR/.log.$(date +%F-%H-%M-%S)
 
-run_sicstus() {
-    echo ':- discontiguous register/1, wire/1.' \
-        && $IVL $@ -O >(cat) =($IVLPP $FILENAME) &>$LOGFILE \
-            || echo 'parse_failed(true).' 
+print_IR() {
+    (  echo '% vim: set ft=prolog\n:- discontiguous register/1, wire/1.' && $IVL $@ -O >(cat) =($IVLPP $FILENAME) &>$LOGFILE && sed -n --posix 's|^[ \t]*//[ \t]*@annot{\(.*\)}[^}]*|\1.|p' $FILENAME ) || echo 'parse_failed(true).' 
 }
 
+IR_FILE=${FILENAME:A:h}/.${FILENAME:t:r:r:r}.pl
 
-# # interpret
-# pushd $THIS_DIR
-# ( sicstus \
-#       -f --noinfo --nologo \
-#       -l 'src/verilog.pl' \
-#       --goal '(run -> halt; halt(1)).' \
-#       -- =(run_sicstus $@) \
-#       && rm -f $LOGFILE ) || ( echo "[ERROR]" 1>&2 && cat $LOGFILE )
-# popd
+print_IR $@ > $IR_FILE
+last_err=$?
 
-# compile & run
-make -s && (($APP =(run_sicstus $@) && rm -f $LOGFILE ) || (echo "[ERROR]"; cat $LOGFILE; exit 1))
+if [[ $last_err -ne 0 ]]; then
+    echo "error while generating the IR file"
+    exit 1
+fi
+
+if $INTERPRETER; then
+    pushd $THIS_DIR
+
+    sicstus \
+        -f --noinfo --nologo \
+        -l 'src/verilog.pl' \
+        --goal '(main -> halt; halt(1)).' \
+        -- $IR_FILE
+    
+    last_err=$?
+
+    if [[ $last_err -ne 0 ]]; then
+        echo "[PROLOG ERROR]" 1>&2
+        cat $LOGFILE
+        exit 1 
+    else
+        rm -f $LOGFILE
+    fi
+
+    popd
+else
+    if make -s && $APP $IR_FILE
+    then
+        rm -f $LOGFILE
+    else
+        echo "[PROLOG ERROR]" 1>&2
+        cat $LOGFILE
+        exit 1 
+    fi
+fi
